name: 🪲 Bug
description: Create a new bug issue
title: '[Bug]: '
labels: ['bug', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! ❤️
  - type: markdown
    attributes:
      value: |
        > Please don't forget to set assignees and a priority label
        ### Priority
        > For priority pleaase check the following table
  - type: markdown
    attributes:
      value: |
        |Severity/Type||Frequency|||
        |--|--|--|--|--|
        ||All users|Most users|Some users|Few users|
        | Very likely |![](https://singlecolorimage.com/get/462190/100x25) |![](https://singlecolorimage.com/get/BB262A/100x25)|![](https://singlecolorimage.com/get/BB262A/100x25)|![](https://singlecolorimage.com/get/D19B31/100x25)|
        |Likely|![](https://singlecolorimage.com/get/BB262A/100x25)|![](https://singlecolorimage.com/get/BB262A/100x25)|![](https://singlecolorimage.com/get/D19B31/100x25)|![](https://singlecolorimage.com/get/D19B31/100x25)|
        |Moderate|![](https://singlecolorimage.com/get/BB262A/100x25)|![](https://singlecolorimage.com/get/D19B31/100x25)|![](https://singlecolorimage.com/get/D19B31/100x25)|![](https://singlecolorimage.com/get/3B8639/100x25)|
        |Unlikely|![](https://singlecolorimage.com/get/D19B31/100x25)|![](https://singlecolorimage.com/get/D19B31/100x25)|![](https://singlecolorimage.com/get/3B8639/100x25)|![](https://singlecolorimage.com/get/3B8639/100x25)|
        |Rare|![](https://singlecolorimage.com/get/D19B31/100x25)|![](https://singlecolorimage.com/get/3B8639/100x25)|![](https://singlecolorimage.com/get/3B8639/100x25)|![](https://singlecolorimage.com/get/3B8639/100x25)|
  - type: checkboxes
    attributes:
      label: To avoid duplicates, please check the following list.
      options:
        - label: The issue is present on the last version.
          required: true
        - label: I have searched for [issues](https://github.com/reservamos/whitelabel-funnel/issues) from this repo and think that is not a duplicate.
          required: true
  - type: textarea
    attributes:
      label: 😯 Current behavior
      description: Describe what happens instead of the expected behavior.
    validations:
      required: true
    id: CurrentBehavior
  - type: textarea
    attributes:
      label: 🤔 Expected behavior
      description: Describe what should happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🕹 Steps to reproduce
      description: Issues without steps take longer to be resolved.
      placeholder: |
        1. Do something with x
        2. Then click inside the y
        3. Look inside the z
      render: bash
  - type: textarea
    attributes:
      label: 🕵🏻‍♂️ Evidence
      description: |
        Please provide an example image or video and an unambiguous set of steps to reproduce this error. 
        Include code to reproduce if relevant.
  - type: dropdown
    attributes:
      label: 🌎 Browser
      multiple: true
      options:
        - 'Firefox'
        - 'Google chorme'
        - 'Microsoft Edge'
        - 'Opera'
        - 'Safari'
        - 'Other'
  - type: dropdown
    attributes:
      label: 🖥 OS
      multiple: true
      options:
        - 'Windows'
        - 'macOS'
        - 'Linux'
        - 'iOS'
        - 'Android'
        - 'Other'
  - type: textarea
    attributes:
      label: 🔗 Environment specific versions
      placeholder: |
        Firefox: 1.0.0
        Google chorme: 1.0.0
        NPM: 16.0.0
